name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: ghcr.io/huww98/master-thesis-env:master
    steps:
      - uses: actions/checkout@v3

      - name: Compile LaTeX document
        run: make

      - uses: actions/upload-artifact@v3
        with:
          name: thesis
          path: build/main.pdf
