name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: ghcr.io/huww98/master-thesis-env:master
    steps:
      - uses: actions/checkout@v3

      - name: count words
        run: texcount -merge main.tex

      - name: Compile LaTeX document
        env:
          OPENCV_IO_ENABLE_OPENEXR: "1"
        run: make

      - uses: actions/upload-artifact@v3
        with:
          name: thesis
          path:
            - build/main.pdf
            - build/blind.pdf
